project:
  type: book
  output-dir: docs
	
book:
  title: "CityFoodPolicy"
  author: "Becca Jablonski, Jasmine Dillon, Randall Boone, Frank Ge, Miguel Gomez, Jon Guez, McKenna Short, Rebecca Whipple Silverstein, Allison Bauman"
  cover-image: images/cover.png
  date: "December 2025"
  favicon: images/favicon.png
  repo-url: https://github.com/FoodSystemsModeling/CityFoodPolicy
  page-navigation: true
  
  # Book structure
  chapters:
    - index.qmd
    - cityfoodpolicies.qmd
    - research_question.qmd
    - research_approach.qmd
    - part: "Dry beans"
      chapters: 
      - drybeans/model_boundaries.qmd
      - drybeans/data_inputs.qmd
      - drybeans/model_parameterization.qmd
      - drybeans/agent_behavior_decisions.qmd
      - drybeans/model_validation.qmd
      - drybeans/model_outputs.qmd
    - part: "Beef"
      chapters: 
        - beef/beef.qmd
    - part: "Greens"
      chapters:
        - greens/greens.qmd
    - part: "Appendices"
      chapters:
        - appendix/glossary.qmd
        - appendix/appendix.qmd

bibliography: references.bib

format: html

knitr: 
  opts_chunk: 
    message: false
    warning: false
    eval: false
	
  


