project:
  type: book
  output-dir: _book
	
book:
  title: "CityFoodPolicy"
  author: "Becca Jablonski, Randall Boone, Jasmine Dillon, Frank Ge, Miguel Gomez, Jon Guez, McKenna Short, Rebecca Whipple Silverstein, Allison Bauman"
  cover-image: images/cover.png
  date: "November 2025"
  favicon: images/favicon.png
  repo-url: https://github.com/FoodSystemsModeling/CityFoodPolicy
  page-navigation: true
  
  # Book structure
  chapters:
    - index.qmd
    - cityfoodpolicies.qmd
    - research_question.qmd
    - nys_supply_chains.qmd
    - modeling_approach.qmd
    - part: "Dry beans"
      chapters: 
      - drybeans/supply_chain.qmd
      - drybeans/agricultural_production.qmd
      - drybeans/farmgate.qmd
      - drybeans/supply_chain_margins.qmd
      - drybeans/institutional_purchasing_NYC.qmd
      - drybeans/model_data_documentation.qmd
    - part: "Beef"
      chapters: 
        - beef/beef.qmd
    - part: "Greens"
      chapters:
        - greens/greens.qmd
    - part: "Appendices"
      chapters:
        - appendix/appendix.qmd

bibliography: references.bib

format: html

knitr: 
  opts_chunk: 
    message: false
    warning: false
    
    # Add echo: true or false for different versions with and without the code



